//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionSupport.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class support {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal support() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestionSupport.Resources.support", typeof(support).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FechaCitaGaraje.
        /// </summary>
        public static string AppointmentGarageDateUTC {
            get {
                return ResourceManager.GetString("AppointmentGarageDateUTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recargar.
        /// </summary>
        public static string btnReload {
            get {
                return ResourceManager.GetString("btnReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presupuesto.
        /// </summary>
        public static string BudgetNumber {
            get {
                return ResourceManager.GetString("BudgetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado Presupuesto.
        /// </summary>
        public static string BudgetStatusName {
            get {
                return ResourceManager.GetString("BudgetStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string cancelButton {
            get {
                return ResourceManager.GetString("cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Cancelacion.
        /// </summary>
        public static string CancellationDateUTC {
            get {
                return ResourceManager.GetString("CancellationDateUTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Cancelacion.
        /// </summary>
        public static string CancellationTypeName {
            get {
                return ResourceManager.GetString("CancellationTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string cancelRemove {
            get {
                return ResourceManager.GetString("cancelRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bastidor.
        /// </summary>
        public static string CarFrame {
            get {
                return ResourceManager.GetString("CarFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente.
        /// </summary>
        public static string ClientId {
            get {
                return ResourceManager.GetString("ClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Cliente.
        /// </summary>
        public static string ClientName {
            get {
                return ResourceManager.GetString("ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Cliente.
        /// </summary>
        public static string ClientType {
            get {
                return ResourceManager.GetString("ClientType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Cliente.
        /// </summary>
        public static string ClientTypeName {
            get {
                return ResourceManager.GetString("ClientTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentarios.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        public static string confirmRemove {
            get {
                return ResourceManager.GetString("confirmRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha gestion.
        /// </summary>
        public static string CreatedOnUTC {
            get {
                return ResourceManager.GetString("CreatedOnUTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Solicitud.
        /// </summary>
        public static string CustomerRequestDateUTC {
            get {
                return ResourceManager.GetString("CustomerRequestDateUTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Desinstalacion.
        /// </summary>
        public static string DeinstallationDateUTC {
            get {
                return ResourceManager.GetString("DeinstallationDateUTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Equipo.
        /// </summary>
        public static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Propietario Equipo.
        /// </summary>
        public static string DeviceOwner {
            get {
                return ResourceManager.GetString("DeviceOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Orden.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentario Garaje.
        /// </summary>
        public static string GarageComment {
            get {
                return ResourceManager.GetString("GarageComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha instalacion.
        /// </summary>
        public static string InstallationDateUTC {
            get {
                return ResourceManager.GetString("InstallationDateUTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  Instalador.
        /// </summary>
        public static string InstallerName {
            get {
                return ResourceManager.GetString("InstallerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Se reutiliza el dispositivo?.
        /// </summary>
        public static string IsDeviceReused {
            get {
                return ResourceManager.GetString("IsDeviceReused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Sim Cancelada?.
        /// </summary>
        public static string IsSimCancelled {
            get {
                return ResourceManager.GetString("IsSimCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Es Transferencia?.
        /// </summary>
        public static string IsTransfer {
            get {
                return ResourceManager.GetString("IsTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ultimo en actualizar la orden.
        /// </summary>
        public static string LastUpdateSupportOperatorName {
            get {
                return ResourceManager.GetString("LastUpdateSupportOperatorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación equipo.
        /// </summary>
        public static string LocationName {
            get {
                return ResourceManager.GetString("LocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Num. Pedido.
        /// </summary>
        public static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo estado .
        /// </summary>
        public static string OrderStatusTypeId {
            get {
                return ResourceManager.GetString("OrderStatusTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo estado.
        /// </summary>
        public static string OrderStatusTypeName {
            get {
                return ResourceManager.GetString("OrderStatusTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a orden soporte.
        /// </summary>
        public static string OrderSupportOperatorName {
            get {
                return ResourceManager.GetString("OrderSupportOperatorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion Periféricos.
        /// </summary>
        public static string PeripheralsDescription {
            get {
                return ResourceManager.GetString("PeripheralsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vehículo Anterior.
        /// </summary>
        public static string PreviousVehicleName {
            get {
                return ResourceManager.GetString("PreviousVehicleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vehiculo Remplazado.
        /// </summary>
        public static string ReplacedVehicleName {
            get {
                return ResourceManager.GetString("ReplacedVehicleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instalador.
        /// </summary>
        public static string selectInstallerId {
            get {
                return ResourceManager.GetString("selectInstallerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Orden de Trabajo.
        /// </summary>
        public static string selectWorkOrderId {
            get {
                return ResourceManager.GetString("selectWorkOrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subflota.
        /// </summary>
        public static string SubfleetName {
            get {
                return ResourceManager.GetString("SubfleetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentarios.
        /// </summary>
        public static string support_order_Comments {
            get {
                return ResourceManager.GetString("support_order_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que quieres eliminar esta orden?.
        /// </summary>
        public static string supportorder_message_removecancelorder {
            get {
                return ResourceManager.GetString("supportorder_message_removecancelorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Cancelado.
        /// </summary>
        public static string supportorder_title_removecancelorder {
            get {
                return ResourceManager.GetString("supportorder_title_removecancelorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicio.
        /// </summary>
        public static string TextDeviceName {
            get {
                return ResourceManager.GetString("TextDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subflota.
        /// </summary>
        public static string TextSubfleetName {
            get {
                return ResourceManager.GetString("TextSubfleetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error al realizar la solicitud.
        /// </summary>
        public static string txt_error_aplicacion {
            get {
                return ResourceManager.GetString("txt_error_aplicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vehiculo.
        /// </summary>
        public static string VehicleId {
            get {
                return ResourceManager.GetString("VehicleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Km.
        /// </summary>
        public static string VehicleKms {
            get {
                return ResourceManager.GetString("VehicleKms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vehiculo.
        /// </summary>
        public static string VehicleName {
            get {
                return ResourceManager.GetString("VehicleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Firmware.
        /// </summary>
        public static string VersionFW {
            get {
                return ResourceManager.GetString("VersionFW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OrdenTrabajo.
        /// </summary>
        public static string WorkOrderName {
            get {
                return ResourceManager.GetString("WorkOrderName", resourceCulture);
            }
        }
    }
}
